version: "3"
services:
  go-docker-image:
    build: ./
    ports:
      - '80:80'
    volumes:
      - ./:/app
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    volumes:
      - 'rabbitmq_data:/data'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
volumes:
  rabbitmq_data: